language: php

# list any PHP version you want to test against
php:
  - 7.1

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - ./deploy.sh ${FTP_USER} ${FTP_PASSWORD} ${FTP_SITE} ${FTP_PATH}