name: build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Composer install
        uses: docker://composer:1.9.1
        with:
          args: install
      - name: Deploy with github-pages
        uses: JamesIves/github-pages-deploy-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: build # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          BUILD_SCRIPT: npm install && npm run-script build