name: build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Composer install
        uses: MilesChou/composer-action/7.3@master
        with:
          args: install --no-dev --prefer-dist
      - uses: docker://php:7.3-alpine
