name: build

on:
  push:
    branches:
      - master
    tags:
      - '!refs/tags/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Composer install
        uses: MilesChou/composer-action/7.2/install@master
      - name: Create release zip
        uses: MilesChou/composer-action/7.2@master
        with:
          args: run-script post-install-cmd